services:
  banking-frontend:
    image: ghcr.io/myselfsudhir/banking-frontend/banking-frontend:latest
    container_name: banking-frontend
    ports:
      - "3000:80"
    networks:
      - banking-network
    depends_on:
      - api-gateway

  authentication-service:
    image: ghcr.io/myselfsudhir/banking-project/authentication-service:latest
    container_name: authentication-service
    ports:
      - "8086:8086"
    networks:
      - banking-network
    environment:
      SPRING_PROFILES_ACTIVE: docker

  account-service:
    image: ghcr.io/myselfsudhir/banking-project/account-service:latest
    container_name: account-service
    ports:
      - "8081:8081"
    networks:
      - banking-network
    environment:
      SPRING_PROFILES_ACTIVE: docker

  payment-service:
    image: ghcr.io/myselfsudhir/banking-project/payment-service:latest
    container_name: payment-service
    ports:
      - "8083:8083"
    networks:
      - banking-network
    environment:
      SPRING_PROFILES_ACTIVE: docker

  transaction-service:
    image: ghcr.io/myselfsudhir/banking-project/transaction-service:latest
    container_name: transaction-service
    ports:
      - "8082:8082"
    networks:
      - banking-network
    environment:
      SPRING_PROFILES_ACTIVE: docker

  fraud-detection-service:
    image: ghcr.io/myselfsudhir/banking-project/fraud-detection-service:latest
    container_name: fraud-detection-service
    ports:
      - "8084:8084"
    networks:
      - banking-network
    environment:
      SPRING_PROFILES_ACTIVE: docker

  notification-service:
    image: ghcr.io/myselfsudhir/banking-project/notification-service:latest
    container_name: notification-service
    ports:
      - "8085:8085"
    networks:
      - banking-network
    environment:
      SPRING_PROFILES_ACTIVE: docker

  api-gateway:
    image: ghcr.io/myselfsudhir/banking-project/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - banking-network
    environment:
      SPRING_PROFILES_ACTIVE: docker

# networks:
#   banking-network:
#     external: true
#     name: bankingproject_banking-network
