name: Banking Project CI

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:

  build-and-docker:
    name: Build & Docker ${{ matrix.service }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - account-service
          - api-gateway
          - authentication-service
          - fraud-detection-service
          - notification-service
          - payment-service
          - transaction-service

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build ${{ matrix.service }}
        working-directory: ./${{ matrix.service }}
        run: mvn clean package -DskipTests

      - name: Build Docker image
        working-directory: ./${{ matrix.service }}
        run: |
          docker build \
            -t banking/${{ matrix.service }}:${{ github.sha }} \
            -t banking/${{ matrix.service }}:latest \
            .